{{- if .Values.persistence.enabled -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "interwebs-speed.fullname" . }}-pv
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.size }}
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "interwebs-speed.fullname" . }}-pvc
  labels:
    {{- include "interwebs-speed.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}
