name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pipx & poetry
      run: |
        sudo apt update
        sudo apt install pipx
        pipx ensurepath
        pipx install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Run pytest
      run: |
        poetry run pytest

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          cassiofariasmachado/interwebs-speed:latest
          cassiofariasmachado/interwebs-speed:${{ github.sha }}